### PR TITLE
Show data by list

### PR DESCRIPTION
**Pull request by shauryaaher**
Show data as a `<li></li>` list.

### CODE REVIEW

**Comment by shauryaaher** [comment]
@darrt2008 Awaiting your review.

**Comment by shauryaaher** [comment]
@darrt2008 Review is required. Please review this PR.

**Review by darrt2008 — APPROVED** [review]
Looks Good!

**Review by darrt2008 — APPROVED** [review]
Approved.

**Review by darrt2008 — APPROVED** [review]
Approved

**Comment by shauryaaher** [comment]
Gotcha, man.

**Comment by shauryaaher** [comment]
Will deploy tomorrow.

**Review by shauryaaher — COMMENTED** [review]
Goodie.

**Pull request merged**
