### PR TITLE
Create LICENSE

### PR DESCRIPTION
**Pull request by shauryaaher**
A license is good for the repo.

### CODE REVIEW

**Comment by shauryaaher** [comment]
Checks cancelled as they would check and deploy code unnecessarily.

**Comment by shauryaaher** [comment]
@darrt2008 Requesting your review.

**Comment by shauryaaher** [comment]
@darrt2008 This is a license for the repo. Check the commit for more details.

**Comment by shauryaaher** [comment]
@darrt2008 Please review this within today.

**Review by darrt2008 — APPROVED** [review]
👍

**Pull request merged**
